CREATE OR REPLACE PACKAGE BODY TEST_UTIL AS

    FUNCTION TEST_SLEEP RETURN VARCHAR2 AS
        STATUS VARCHAR2(10);
    BEGIN
        DBMS_LOCK.SLEEP(1200);

        STATUS := 'END';
        RETURN STATUS;
    END;

END;
/